info.onCountdownEnd(function () {
    game.gameOver(false)
    game.splash(info.score())
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
    level += 1
    hero.setPosition(10, 10)
    scene.cameraShake(4, 500)
    info.startCountdown(30)
})
let hero: Sprite = null
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77777777777f
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff444777777777777
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff44477777777f777
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff444777777777777
    fffffffffffffffffffee222222222fffffffffffffffffffffffffffffffffe2222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777777777777777
    fffffffffffffffffeee2222222222fffffffffffffffffffffffffffffffffe2222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7777777777777777
    ffffffffffffffffee222222222222fffffffffffffffffffffffffffffffffee222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777444777777777777
    fffffffffffffffee222222ffffffffffffffffffffffffffffffffffffffffff2222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7777444777777777f77
    ffffffffffffffee22222ffffffffffffffffffffffffffffffffffffffffffff2222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77777444777777777777
    ffffffffffffffe22222ffffffffffffffffffffffffffffffffffffffffffffff222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777777777444777777777
    ffffffffffffff2222ffffffffffffffffffffffffffffffffffffffffffffffff2222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77444777744477777777f
    ffffffffffffff2222ffffffffffffffffffffffffffffffffffffffffffffffff2222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777444777f4447777777ff
    ffffffffffffff222222222ffffffffffffffffffffffffffffffffffffffffffff222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77774447fffffffffffffff
    ffffffffffffff222222222222ffffffffe222222ffffffffffffffffffffffffff222fff222222ffffffffefffffffffffffffffffffffffffffffffffffffffffffffff77777777fffffffffffffff
    fffffffffffffff222222222222ffffffe22222222fffffffffffffffffffffffff2222f22222222ffffffef22222fffffffffffffffffffffffffffffffffffffffffff77777777ffffffffffffffff
    fffffffffffffffffffff2222222fffffe222222222ffffffffee2222222fffffff22222222222222ffffee2222222ffffffffffffffffffffffffffffffffffffffffff7444777fffffffffffffffff
    fffffffffffffffffffffff22222ffffee222222222ffffffeee22222222ffffffff2222222ff2222ffffe22222222fffffffffffffffffffffffffffffffffffffffff77444777fffffffffffffffff
    fffffffffffffffffffffffff2222fffe2222fff2222ffffee2222222222ffffffff2222222ff2222ffffe22222222fffffffffffffffffffffffffffffffffffffffff7744477ffffffff222fffffff
    fffffffffffffffffffffffff2222ffff2222fff2222fffff222222ff222ffffffff222222ffff222fffe222222222ffffffffffffffffffffffffffffffffffffffff77777777ffffffff222fffffff
    fffffffffffffffffffffffff2222ffff222ffff2222fffff22222fff2222fffffff22222ffff2222fffe222222222fffffffffffffffffffffffffffffffffffffff77777777fffffffff222fffffff
    ffffffffffffffffffffffffff222ffff222fffff2222ffff2222ffff2222ffffffff2222ff222222fffe222f222ffffffffffffffffffffffffffffffffffffffff777777777fffffffff222fffffff
    ffffffffffffffffffffffffff222ffff222fffff2222ffff222fffff2222ffffffff2222f222222ffffe222fffffffffffffffffffffffffffffffffffffffff77444774447ffffffffff2222ffffff
    ffffffffff2222ffffffffffff222ffff222ffffff222ffff222ffff22222fffffffff222f22222fffff2222fffffffffffffffffffff777777777ffffffff77777444774447ffffffffff2222ffffff
    ffffffffff222222ffffffffff222ffff222ffffff222ffff222ffff222222ffffffff222f22222fffff2222fffffffffffffffff7777777777777777777777777744477444ffffffffffff222ffffff
    ffffffffff2222222222fffff2222ffff222ffffff222ffff222fff2222222ffffffff22222222222fff222ffffffffffffffff77444777777777777777777777777777777fffffffffffff222ffffff
    ffffffffff5555222222222222222ffff222ffffff222ffff2222f222222222fffffff222555222222ff2222fffff222ffffff7774447777777444777777444777777777fffffffffffffff222ffffff
    fffffffffffff5555522222222222ffff222ffffff222ffff22222222222222fffffff222255522222ff2222fffff222fffff77774447777777444777777444777777ffffffffffffffffff222ffffff
    fffffffffffffffff555555555555ffff222ffffff222ffff22222222555522fffffff22225f555555ff222222ff2222fffff77777777777777444777777444777fffffffffffffffffffff222ffffff
    fffffffffffffffffffffffffffffffff255ffffff222fffff52255555f5552fffffff52555ffffffffff22222222222ffff7777777777fffffffffffffffffffffffffffffffffffffffff222ffffff
    fffffffffffffffffffffffffffffffff55fffffff555fffff55555ffffffffffffffff555ffffffffffff2222222225fff777744477fffffffffffffffffffffffffffffffffffffffffff222ffffff
    fffffffffffffffffffffffffffffffffffffffff5555ffffffffffffffffffffffffffffffffffffffff55222222555fff77774447ffffffffffffffffffffffffffffffffffffffffffff222ffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff55555555ffff77777444fffffffffffffffffffffffffffffffffffffffffffff222ffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffff7744477777777ffffffffffffffffffffffffff7444777777fffffffffffffffffffffffffffffffffffffffffffff2222fffff
    fffffffffffffffffffffffffffffffffffffffffffffffff7777777777444777777777777777777777777777777ff77744477777ffffffffffffffffffffffffffffffffffffffffffffff2222fffff
    ffffffffffffffffffffffffffffffffffffffffffffff7777777777777444777777777777444777777744477777777774447777ffffffffffffffffffffffffffffffffffffffffffffffff222fffff
    fffffffffffffffffffffffffffffffffffffffffff774447777774447777777777444777744477777774447777777777777777ffffffffffffffffffffffffffffffffffffffffffffffffe222fffff
    fffffffffffffffffffffffffffffffffffffffff7777444777777444777777777744477774447777777444777444777777777fffffffffffffffffffffffffffffffffffffffffffffffffe222fffff
    fffffffffffffffffffffffffffffffffffffff7777774447777774447777ffff774447777777777777777777744477777777ffffffffffffffffffffffffffffffffffffffffffffffffffe222fffff
    ffffffffffffffffffffffffffffffffffffff7744477777777777fffffffffffffffffffffffffffffffff777444777777ffffffffffffffffffffffffffffffffffffffffffffffffffffe222fffff
    ffffffffffffffffffffffffffffffffffff77774447777777fff222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe2222ffff
    fffffffffffffffffffffffffffffffffff7777744477777ffffe222222222ffffffffee22222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe2222ffff
    ffffffffffffffffffffffffffffffffff777777777777ffffffe2222222222fffffeee2222222fffffeee222222222222ffffffffffeeeee222222ffffffffffffffffffffffffffffffffee222ffff
    fffffffffffffffffffffffffffffffff44477744477ffffffffe2222222222ffffe22222222222fffeee22222222222222ffffffffee2222222222fffffffffe222222222222ffffffffffee222ffff
    fffffffffffffffffffffffffffffffff4447774447fffffffffe22222ff2222ffe222222ff22222ffee222222222222222ffffffffe22222222222fffffffffe2222222222222ffffffffffe222ffff
    ffffffffffffffffffffffffffffffff7444777444ffffffffffe2222fff22222f22222fffff22222fe22222fffffff2222ffffffffe222222f2222ffffffffe22222222222222ffffffffffe222ffff
    fffffffffffffffffffffffffffffff777777777fffffffffffff2222ffff222222222fffffff2222ff2222fffffffff222ffffffffffffff22222fffffffffe2222ffff222222ffffffffffffffffff
    fffffffffffffffffffffffffffffff77777777ffffffffffffff222ffffff2222222fffffffff222ff222ffffffffff2222ffffffffffff222222ffffffffee22222222222222ffffffffffffffffff
    ffffffffffffffffffffffffffffff744477777ffffffffffffff222ffffff222222ffffffffff2222f222ffffffffff2222ffffffffffff22222ffffffffffe2222222222222fffffffffffffffffff
    ffffffffffffffffffffffffffff7774447777fffffffffffffff222fffffff22222ffffffffff2222f2222ffffffff222222ffffffffff2222ffffffffffff22222222222ffffffffffffffffffffff
    ffffffffffffffffffffffffff77777444777ffffffffffffffff222fffffff2222ffffffffffff222f2222ffffffff2222222ffffffff22222ffffffffffff222ffffffffffffffffffffffffffffff
    ffffffffffffffffffffffff777777777777fffffffffffffffff222ffffffff222ffffffffffff222ff22222fffff222222222fffffff2222fffffffffffff222ffffffffffffffffffffffffffffff
    ffffffffffffffffffff7777774447777777fffffffffffffffff2555fffffff222ffffffffffff222ff22222222222222f2222fffff22222ffffffffffffff22222ffffffff2222ffffffffffffffff
    fffffffffffffff77777777777444777777ffffffffffffffffff555ffffffff255ffffffffffff222fff222222222222ff22222ffff22222222222222fffff22222222222222222ffffffffe222ffff
    fffffffffff7444777777777774447777ffffffffffffffffffffffffffffffff5fffffffffffff222fffff222222222ffff2222ffff22222222222222ffffff2222222222222222fffffffee225ffff
    ffffffff77774447777777777777777ffffffffffffffffffffffffffffffffffffffffffffffff222fffff555555555fffff222ffff22255222255522ffffffff225522255522fffffffffff2255fff
    fffffff7777744477744477777777fffffffffffffffffffffffffffffffffffffffffffffffffff555ffffffff5fffffffff222ffff5555555555f555fffffffff5555555f555fffffffffff5555fff
    ffffff7777777777774447777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff225ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffff7777777777777444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff555ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffff777777777777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffff777777777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ff7777777777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ff777444777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    f777744477ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    f77774447fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    f7777777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    f777777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    f777777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    f77777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    f77777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `)
music.play(music.stringPlayable("C C5 C5 G C F E D ", 160), music.PlaybackMode.LoopingInBackground)
game.showLongText("Welcome to my maze! Find the treasure before the time runs out!", DialogLayout.Bottom)
scene.setBackgroundImage(img`
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    `)
music.stopAllSounds()
music.play(music.melodyPlayable(music.bigCrash), music.PlaybackMode.UntilDone)
effects.blizzard.startScreenEffect(1000)
scene.cameraShake(4, 1000)
hero = sprites.create(img`
    . . . . c c c c c c . . . . . . 
    . . . c 6 7 7 7 7 6 c . . . . . 
    . . c 7 7 7 7 7 7 7 7 c . . . . 
    . c 6 7 7 7 7 7 7 7 7 6 c . . . 
    . c 7 c 6 6 6 6 c 7 7 7 c . . . 
    . f 7 6 f 6 6 f 6 7 7 7 f . . . 
    . f 7 7 7 7 7 7 7 7 7 7 f . . . 
    . . f 7 7 7 7 6 c 7 7 6 f c . . 
    . . . f c c c c 7 7 6 f 7 7 c . 
    . . c 7 2 7 7 7 6 c f 7 7 7 7 c 
    . c 7 7 2 7 7 c f c 6 7 7 6 c c 
    c 1 1 1 1 7 6 f c c 6 6 6 c . . 
    f 1 1 1 1 1 6 6 c 6 6 6 6 f . . 
    f 6 1 1 1 1 1 6 6 6 6 6 c f . . 
    . f 6 1 1 1 1 1 1 6 6 6 f . . . 
    . . c c c c c c c c c f . . . . 
    `, SpriteKind.Player)
hero.setPosition(10, 10)
controller.moveSprite(hero)
scene.cameraFollowSprite(hero)
let level = 1
info.setScore(100)
info.startCountdown(30)
game.onUpdateInterval(1000, function () {
    info.changeScoreBy(-1)
})
forever(function () {
    if (level == 1) {
        tiles.setCurrentTilemap(tilemap`level1`)
    }
    if (level == 2) {
        tiles.setCurrentTilemap(tilemap`level2`)
    }
    if (level == 3) {
        tiles.setCurrentTilemap(tilemap`level4`)
    }
    if (level == 4) {
        game.gameOver(true)
    }
})
